//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.KSyanpse.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.KSyanpse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   KSynapse 공통 라이브러리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KSynapse_Common_Library_Description {
            get {
                return ResourceManager.GetString("KSynapse_Common_Library_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공통 라이브러리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KSynapse_Common_Library_FriendlyName {
            get {
                return ResourceManager.GetString("KSynapse_Common_Library_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LevelChoice_LevelDebug_FriendlyName {
            get {
                return ResourceManager.GetString("LevelChoice_LevelDebug_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LevelChoice_LevelError_FriendlyName {
            get {
                return ResourceManager.GetString("LevelChoice_LevelError_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LevelChoice_LevelFatal_FriendlyName {
            get {
                return ResourceManager.GetString("LevelChoice_LevelFatal_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LevelChoice_LevelInfo_FriendlyName {
            get {
                return ResourceManager.GetString("LevelChoice_LevelInfo_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LevelChoice_LevelTrace_FriendlyName {
            get {
                return ResourceManager.GetString("LevelChoice_LevelTrace_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LevelChoice_LevelWarning_FriendlyName {
            get {
                return ResourceManager.GetString("LevelChoice_LevelWarning_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_Config_Description {
            get {
                return ResourceManager.GetString("WriteLog_Config_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_Config_FriendlyName {
            get {
                return ResourceManager.GetString("WriteLog_Config_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 레벨 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_Level_Description {
            get {
                return ResourceManager.GetString("WriteLog_Level_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   레벨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_Level_FriendlyName {
            get {
                return ResourceManager.GetString("WriteLog_Level_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_Message_Description {
            get {
                return ResourceManager.GetString("WriteLog_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_Message_FriendlyName {
            get {
                return ResourceManager.GetString("WriteLog_Message_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Init, End 등 현재 과제 진행 State과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_State_Description {
            get {
                return ResourceManager.GetString("WriteLog_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행 상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_State_FriendlyName {
            get {
                return ResourceManager.GetString("WriteLog_State_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   하위플로우 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_SubflowName_Description {
            get {
                return ResourceManager.GetString("WriteLog_SubflowName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   하위플로우 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_SubflowName_FriendlyName {
            get {
                return ResourceManager.GetString("WriteLog_SubflowName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트랜잭션 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_TransactionName_Description {
            get {
                return ResourceManager.GetString("WriteLog_TransactionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트랜잭션 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_TransactionName_FriendlyName {
            get {
                return ResourceManager.GetString("WriteLog_TransactionName_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트랜잭션 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_TransactionNumber_Description {
            get {
                return ResourceManager.GetString("WriteLog_TransactionNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트랜잭션 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteLog_TransactionNumber_FriendlyName {
            get {
                return ResourceManager.GetString("WriteLog_TransactionNumber_FriendlyName", resourceCulture);
            }
        }
    }
}
